compressionLevel: 0 # faster, but less yarn cache compression; git compression is better than gzip

enableGlobalCache: true # local cache is only useful when running zero installs

nodeLinker: node-modules

tsEnableAutoTypes: true

yarnPath: .yarn/releases/yarn-4.5.1.cjs
